AddCommand("", "	...	",	false	,	-1	, 	-1	,	-1	,	timeline_fieldLook	, 	1.5	, 	0	);
AddCommand("Vera	", "	Que bom que resolvi passar por aqui hoje.	",	false	,	bg_blackBG	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("Vera	", "	O campo levemente iluminado onde é plantado trigo, a casa \ncom algumas luzes ligadas ao fundo.	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("Vera	", "	​É admirável.​	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("Vera	", "	​Me deixa feliz que o dono de várias terras deixa um clima \ntão familiar na propriedade onde mora.​	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("Vera	", "	Nada muito extravagante, nem mesmo a enorme garagem \nque guarda as máquinasagrícolas chama muito a atenção.	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("Vera	", "	*Sigh*	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	1	, 	0	);
AddCommand("Vera	", "	​A tranquilidade de aproveitar uma cena como essa me \nengasga.​	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("Vera	", "	​Tudo o que eu consegui até agora, essa tranquilidade \nque eu vivo,​	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("Vera	", "	​Parece uma recompensa por ter persistido.​	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("Vera	", "	​Ter me mudado pra essa cidade no interior foi o que me \ndeu a oportunidade de sentir essa brisa.​	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("Vera	", "	​Mas isso engasga por que eu não aproveitei enquanto meus \npais estavam vivos.​	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("Vera	", "	​Nós não conhecíamos nada além da tranquilidade.​	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	2	, 	0	);
AddCommand("Vera	", "	Não foi para isso que eu vim aqui.	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("Vera	", "	Eu não devia pensar tanto nisso.	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("Vera	", "	​Mas todo dia traz um lembrete daquele dia.​	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("Vera	", "	É difícil evitar.	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("Vera	", "	\"?\"	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("Vera	", "	\"A brisa parou mas--\"	",	false	,	-1	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("Vera	", "	Parece que algo disparou na direção da fazenda, mas \nnão deu pra ver o que era.	",	false	,	-1	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("Vera	", "	Eu prefiro acreditar que não é nada demais, mas acho \nmelhor continuar meu caminho.	",	false	,	-1	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("", "	...	",	false	,	-1	, 	-1	,	-1	,	timeline_fieldRunLeft	, 	1	, 	0	);