AddCommand("", "...	",	false	,	-1	, 	-1	,	-1	,	timeline_fieldLook	, 	1.5	, 	0	);
AddCommand("", "Que bom que resolvi passar por aqui hoje.	",	false	,	bg_blackBG	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("", "O campo levemente iluminado onde é plantado trigo, a casa \ncom algumas luzes ligadas ao fundo.	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("", "É admirável.​	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("", "Me deixa feliz que o dono de várias terras deixa um clima \ntão familiar na propriedade onde mora.​	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("", "Nada muito extravagante, nem mesmo a enorme garagem \nque guarda as máquinasagrícolas chama muito a atenção.	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("Vera", "*Sigh*	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	1	, 	0	);
AddCommand("", "A tranquilidade de aproveitar uma cena como essa me engasga.​	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("", "Tudo o que eu consegui até agora, essa tranquilidade \nque eu vivo,​	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("", "Parece uma recompensa por ter persistido.​	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("", "Ter me mudado pra essa cidade no interior foi o que me \ndeu a oportunidade de sentir essa brisa.​	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("", "Mas isso engasga por que eu não aproveitei enquanto meus \npais estavam vivos.​	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("", "Nós não conhecíamos nada além da tranquilidade.​	",	false	,	bg_field_night	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("", "...",	false	,	-1	, 	-1	,	-1	,	timeline_fieldRunLeft	, 	2	, 	0	);