AddCommand("	Vera	", "	​Há um quantidade enorme de livros aqui.​	",	false	,	-1	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("	Vera	", "	​Esse aqui não tem nome.​	",	false	,	-1	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("	Vera	", "	​É um colagem de notícias do que aconteceu no início do\nano passado!​	",	false	,	-1	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("	Vera	", "	\'Dia 22 de fevereiro, Yanukovych é deposto por votos do \nparlamento.\'	",	false	,	-1	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("	Vera	", "	​Os protestos acabaram dias depois, mas as coisas só \nacalmaram de verdade no final do ano.​	",	false	,	-1	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("	Vera	", "	​Depois do cessar fogo entre a Rússia e a Ucrânia​	",	false	,	-1	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("	Vera	", "	​Eles nunca pensaram na gente.​	",	false	,	-1	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("	Vera	", "	​O olhando bem agora, todos os livros parecem estar em russo.​	",	false	,	-1	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("	Vera	", "	\"?\"	",	false	,	-1	, 	-2	,	-1	,	-1	, 	0	, 	0	);
AddCommand("	Vera	", "	​Parece seguro agora.​	",	false	,	-1	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("	Vera	", "	​Eu vou sair antes que alguém chegue.​	",	false	,	bg_blackBG	, 	-1	,	-1	,	-1	, 	0	, 	0	);