truncate[0,0] = "Correr até o distrito comercial";
truncate[0,1] = ir_para_cidade;
truncate[1,0] = "Se esconder na casa";
truncate[1,1] = ir_para_a_casa;
AddCommand("	Vera	", "	...	",	false	,	bg_nightStreet_1	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("	Vera	", "	​Aquilo está ali.​	",	false	,	bg_nightStreet_2	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("	Vera	", "	​Parece estar me esperando.​	",	false	,	bg_nightStreet_3	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("	Vera	", "	...	",	false	,	bg_nightStreet_1	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("	Vera	", "	​Eu preciso sair daqui.​	",	false	,	bg_nightStreet_2	, 	-1	,	-1	,	-1	, 	0	, 	0	);
AddCommand("	Vera	", "		",	false	,	-1	, 	-1	,	-1	,	-1	, 	0	, 	truncate	);